version: '3.4'

networks:
  network:

services:
  nginx:
    image: nginx:latest
    container_name: server-etos-indonusa
    restart: unless-stopped
    ports:
  # frontend port 
  # app port
      # - "8100:8100" # host
      # - "8101:8101" # sales
      # - "8102:8102" # spv
      # - "8103:8103" # accounting
      # - "8104:8104" # payroll
      # - "8105:8105" # management

   # mfe port
      # - "8200:8200" # auth 

  # services port
      - "8900:8900" # auth

  # fullstack port

    volumes:
      - ./code/indonusa/laravel:/home/www-data/indonusa
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      # - proxy
      - php
      - redis
      - mysql
      - mongodb
    networks:
      - network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-etos-indonusa
    restart: unless-stopped
    volumes:
      - ./code/indonusa/laravel:/home/www-data/indonusa
    ports:
      - "8199:9000"
    networks:
      - network
  redis:
    image: redis:latest
    container_name: etos-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass etos
    volumes:
      - ./database/redis:/data
    ports:
      - "8379:6379"
    networks:
      - network
  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: unless-stopped
    container_name: mysql-etos-indonusa
    ports:
      - "8306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_DATABASE: etos
      MYSQL_USER: etos
      MYSQL_PASSWORD: etos
      MYSQL_ROOT_PASSWORD: etos
      SERVICE_TAGS: dev
      SERVICE_NAME: database

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb-etos-indonusa
    environment:
      MONGO_INITDB_ROOT_USERNAME: etos
      MONGO_INITDB_ROOT_PASSWORD: etos
    ports:
      - 28017:27017
    volumes:
      - ./database/mongodb:/data/db

  # proxy:
  #     image: 'jc21/nginx-proxy-manager:latest'
  #     container_name: proxy
  #     restart: unless-stopped
  #     ports:
  #       - '80:80'
  #       - '81:81'
  #       - '443:443'
  #     volumes:
  #       - ./proxy/data:/data
  #       - ./proxy/letsencrypt:/etc/letsencrypt
  #     networks:
  #     - network
